### ISSUE TITLE
validateReceipt() fails

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#27]
I've called `retrieveProducts()`, followed by `purchaseProduct()` (for the first product returned by `retrieveProducts()`. The Google Play Purchase dialog opens, I click 1-tap-buy and it says "success". The dialog closes and I get back this error message.

Here's the full error message:

> Exception from server - validateReceipt() :  {"message":"The Token data sent is not correct or Google service is temporarily down","type":"invalid_request","api_error_code":"invalid_request","error_code":"operation_not_supported","error_msg":"The Token data sent is not correct or Google service is temporarily down","http_status_code":400}

I have absolutely no clue what to make of it. I highly doubt that the "Google service" is down and I'm not creating the token so I wouldn't know what could be wrong with it.

Any idea what went wrong here?

**Comment by cb-saisrikant** [comment]
Hi Phillip, As mentioned over mail, this error is due to pub/sub API not enabled in Google cloud. Please enable this and confirm if still you are getting this error. Thanks

**Comment by ciriousjoker** [comment]
I'm sorry I forgot to close this. In our case, we had two Google Cloud Platform projects, one for the app and another one for the PlayStore connection and I accidentally picked the wrong project. Everything worked flawlessly with the correct config.
