### ISSUE TITLE
any one say what value i put sdk_key

### ISSUE THREAD

**Issue by maheshsystimanx** [chargebee/chargebee-android#30]

**Comment by cb-saisrikant** [comment]
Hi, The value of SDK key is the App id that is available in the Chargebee site. To get this, please go to the Sync Overview page of the Chargebee web app, click Set up notifications and use the generated [App ID](https://www.chargebee.com/docs/1.0/mobile-playstore-notifications.html#app-id) value as SDK Key.

**Comment by maheshsystimanx** [comment]
Hi, i  try to search sdk_key in my charge bee demo account.that sync menu not able to find that site.



here i share my user name also.

My account details:



Mahesh ***@***.***





https://systimanxdemo-test.chargebee.com







and also i refer that android sdk in following github.i refer the code.that code need following details.i put the details for below code



var site: String = "systimanxdemo.chargebee.com"
var publishableApiKey: String = "test_RVrhtiJuetHjOXnaLsb2272BlTxXuPEs"
var encodedApiKey: String = "test_RVrhtiJuetHjOXnaLsb2272BlTxXuPEs"
var sdkKey: String = "test_RVrhtiJuetHjOXnaLsb2272BlTxXuPEs"
var baseUrl: String = "systimanxdemo-test"
var allowErrorLogging: Boolean = true
var version: String = CatalogVersion.Unknown.value
var applicationId: String = ""
const val channel: String = "play_store"
var appName: String = "Chargebee"
const val platform: String = "Android"
const val sdkVersion: String = BuildConfig.VERSION_NAME


pls clarify the asap.



Thanks & Regards,

Mahesh,
SystimaNX IT Solutions Pvt Ltd,
M : +91-8754048942,









Confidentiality  Notice: This email (including any attachments) is for the sole use of  the intended recipient(s) and may contain confidential and privileged  information. Any unauthorised review, use, disclosure, dissemination,  forwarding, printing or copying of this email or any action taken in  reliance on this e-mail is strictly prohibited and unlawful. If you are  not the intended recipient, please notify the sender by reply email and  destroy all copies of the original message. Thanks for your cooperation.










---- On Tue, 28 Jun 2022 17:53:48 +0530 cb-saisrikant ***@***.***> wrote ---





Hi, The value of SDK key is the App id that is available in the Chargebee site. To get this, please go to the Sync Overview page of the Chargebee web app, click Set up notifications and use the generated https://www.chargebee.com/docs/1.0/mobile-playstore-notifications.html#app-id value as SDK Key.
