### ISSUE TITLE
retrieveSubscriptions() doesn't support querying for status

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#39]
As per documentation:

> For example, query parameters can be passed as "customer_id" : "id", "subscription_id": "id", or "status": "active".

In reality and when looking at the code, the function only supports ["customerid", "channel"] as its query parameters.

I assume this paragraph was copied from https://github.com/chargebee/chargebee-ios?

Will this functionality be added at some point? It would nice, so we don't need to filter the result we get back manually.

Also, does a status of "active" also include "pending", since pending cancellation is basically the same as active?

(tested in v1.0.5)

**Comment by cb-amutha** [comment]
Hi,
This issue has been fixed in latest version. Thanks.
