### ISSUE TITLE
Unhandled Exception: com.chargebee.android.exceptions.CBException: length=1; index=1

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#40]
This message is completely useless by itself, but when inspecting the sourcecode, it turns out that it was because we only passed the customer id and not the channel (which is apparently required even if it's not documented anywhere).

Please add a better error message here to check for missing parameters.

Basically, calling `retrieveSubscriptions(["customerid"])`, we get an unknown error with no error message because it's swallowed earlier.

If we pass `retrieveSubscriptions(["customerid", "play_store"])`, everything works flawlessly.

(tested in v1.0.5)

**Comment by cb-amutha** [comment]
This issue has no longer persist in the latest version. Please open a new issue for any issues related. Thanks.
