### ISSUE TITLE
Plan id is always null when calling retrieveSubscriptions()

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#41]
This happens on all the 4 Playstore subscriptions I've created on a test account:
<img width="1045" alt="Bildschirmfoto 2022-06-30 um 00 51 31" src="https://user-images.githubusercontent.com/16866223/176558766-b3b421e6-99ea-46ed-a6ba-487001ab80ea.png">

`it.data.list[...].cb_subscription.id` is always`null`.

Am I missing something here? Is this intentional?

When viewing the subscriptions in the Chargebee Dashboard, they all have correct (or at least existent ids).

(tested in v1.0.5)

**Comment by cb-amutha** [comment]
Hi,
This issue has been fixed in latest version.
Please check and update us. Thanks.
