### ISSUE TITLE
Expose native subscription stream

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#59]
In the past, we got weird errors that the purchase failed. However, the purchase didn't fail for those customers.

The native store sdks already send you a stream of purchases, but if the initial call to purchase() failed for some reason, the subscription is never synced to chargebee.

Could you please expose the purchase stream directly from this package?
We could depend on the billingclient directly, but perhaps that's what lead to those "unknown error"s and "purchase failed"s.

It would be great if the purchase stream could be synced to chargebee automatically, but it would be enough if this package just provided a way of extracting the tokens so we can import them into chargebee ourselves.

**Comment by cb-amutha** [comment]
thanks @ciriousjoker. Implementation is on our way(If network goes wrong during the purchase or any failure happens due to some reason it should re-try the calls and sync with Chargebee. And also try to provide the purchase token in case of failures).

**Comment by ciriousjoker** [comment]
That would be amazing!

After updating our app, many users complained that they've lost access to their subscription. I've already opened tickets with Chargebee support about this, but even if those issues aren't resolved, having a fallback for detecting subscriptions via the native stores would be great to avoid issues in the future.

**Comment by ciriousjoker** [comment]
@cb-amutha 
Does this mean that we will be able to ask `chargebee-android` (exposed through `chargebee-flutter`) if there is a valid subscription in Google Play?

**Example:**
- User has a subscription in Google Play, which is correctly synced to their Chargebee account
- User switches account (same device, same user logged into Google Play)
- User doesn't have a subscription in Chargebee anymore (because that subscription is attached to another user in Chargebee)

**We'd like to do something like this:**

```dart
final hasSubscription = hasChargebeeSubscription ||
    flutterChargebeeSdk.subscriptions.any((subscription) => subscription.isValid);
```

Don't get me wrong, improving the stability of the sync to chargebee is definitely necessary, but it probably won't be enough to guarantee that no user will lose access to their valid store subscription. I frankly don't trust you guys to get it right in every possible edgecase with 100% accuracy.

Also, what about `chargebee-ios`?

**Comment by cb-amutha** [comment]
@ciriousjoker Sorry for the late response. The restore purchase method helps to get if any active subscriptions associated with the particular user’s. Currently, restore purchase method is available for all our SDK’s. 

And also, we are enhancing our sdk to provide another method for validating the receipt with Chargebee in case of any failure happened during the purchase. This improvements already available in iOS SDK [PR link](https://github.com/chargebee/chargebee-ios/pull/60). We are working on other SDK’s to have the same. This will be available in end of June’23. Thanks.
