### ISSUE TITLE
Stuck in BillingManager 2.0.0 beta-1

### ISSUE THREAD

**Issue by zabolotiny** [chargebee/chargebee-android#99]
I've tried to integrate 2.0.0 beta-1 in our app but can't make a purchase.
After debugging I can see that execution goes until line 214 of BillingClintManager.kt 
`val productDetailsParamsList =
                    listOf(productDetailsBuilder.build())`
And nothing happens after it.
No crashes or any activity from the app.

**Comment by cb-aravindradhakrishnan** [comment]
@zabolotiny Could you please confirm if this is a sandbox or live purchase? Additionally, if the tester has logged in directly without accepting the link, there is a chance that the product might not be fetched, or it could be a region mismatch. If needed, we can schedule a call to discuss further.
cc: @cb-haripriyan

**Comment by zabolotiny** [comment]
@cb-aravindradhakrishnan True, that was a sandbox purchase. I had to switch to 1.2.1 which is working fine for this scenario. For now we will use 1.2.1 in the next release and we can schedule a call after that. Please write me an email with your contact so we can schedule a call. yuriy@zabolotin.com

**Comment by cb-anurags** [comment]
Will take over the email
